#!/bin/sh

set -e

BASEDIR=$(dirname "$0")

rm -rf "$BASEDIR/dist"

mkdir "$BASEDIR/dist"

# compress [r]ecursively, with compression level [9]
zip -r9 "$BASEDIR/dist/DeUs-macOS-$(git tag -l | tail -n 1).zip" "$BASEDIR/mac/DeUs.bundle" "$BASEDIR/mac/install" "$BASEDIR/README.md" "$BASEDIR/README.de.md" "$BASEDIR/LICENSE"
